export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const INCREMENT_ITEM_COUNT = "INCREMENT_ITEM_COUNT";
export const DECREMENT_ITEM_COUNT = "DECREMENT_ITEM_COUNT";
export const ADD_TO_SAVED = "ADD_TO_SAVED";
export const REMOVE_FROM_SAVED = "REMOVE_FROM_SAVED";
export const MOVE_TO_CART = "MOVE_TO_CART";
export const MOVE_TO_SAVED = "MOVE_TO_SAVED";
